#!/usr/bin/env bash
# Displays numbers 1 to 100

count=1
while ((count<=100));
do
	if ((count % 3 == 0 && count % 5 == 0));
	then
		echo "FizzBuzz"
	elif ((count % 5 == 0));
	then
		echo "Buzz"
	elif ((count % 3 == 0));
	then
		echo "Fizz"
	else
		echo "$count"
	fi
	count=$((count + 1));
done
