#!/usr/bin/env bash
#This script displays "bad luck" in 4, "good luck" in 8, and "Best School" otherwise

count=1
while ((count <= 10));
do
	if ((count == 4));
	then
		echo "bad luck"
	elif ((count == 8));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count+=1))
done
