#!/usr/bin/env bash
#This script displays 1 to 20, displaying bad luck based on country

count=1
while ((count<=20));
do
	if ((count==4));
	then
		echo count
		echo "bad luck from China"
	elif ((count==9));
	then
		echo count
		echo "bad luck from Japan"
	elif ((count==17));
	then
		echo count
		echo "bad luck from Italy"
	else
		echo count
	fi
	((count+=1))
done
