#!/usr/bin/env bash
#This script displays 1 to 20, displaying bad luck based on country

count=1
while ((count<=20));
do
	echo $count
	case $count in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck form Italy";;
	esac
	((count+=1))
done
